### ISSUE TITLE
A plugin for local search

### ISSUE THREAD

**Issue by egoist** [saberland/saber#138]
#### What problem does this feature solve?

For searching in documentation sites / blogs.

#### What does the proposed API look like?

```js
const search = async keyword => {
	const data = await import('#cache/search.json')
	return fuzzySearch(keyword)
}
```

This plugin doesn't need to include a UI component, leaving that to users / theme authors.

#### How should this be implemented in your opinion?

Similar to https://github.com/christian-fei/Simple-Jekyll-Search

#### Are you willing to work on this yourself?

Yes.

**Comment by krmax44** [comment]
Hmm, especially with this in planning, I feel like `saber-plugin-search`, `saber-plugin-query-posts` and `saber-plugin-feed` have quite an overlap in their functionality. Maybe `saber-plugin-query-posts` should be redone to resemble more of a `saber-plugin-query-pages`, that could give you access to `api.pages` in an elegant and traffic-saving way. Then, `saber-plugin-search` would not be necessary at all, since you could simply create a component in your theme like:

```html
<script>
export default {
  computed: {
    searchResults() {
      // all pages with excerpt, loaded from prerendered JSON files, if not already requested & cached
      // options would allow you to define all available types of requests that will be rendered to JSON files
      const pages = this.$pages.query({ excerpt: true })
      return fuzzySearch(pages, this.searchTerm)
    }
  }
}
</script>
```
