### ISSUE TITLE
Tutorial: Get an error before creating a first page

### ISSUE THREAD

**Issue by AlexisJC** [saberland/saber#543]
#### Steps to reproduce

Follow actual tutorial setup.

#### What is expected?

Get a 404 page when running yarn saber.

#### What is actually happening?

Get a terminal error : `Error in render: "TypeError: Cannot read property 'path' of undefined"`

#### Other relevant information

- Result of running `saber -v`: get an error because it is not installed globally
- Browser version (optional):
- Is Saber a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? yes

**Comment by egoist** [comment]
Yeah that happens when you don't have any pages, for now you can create a page to work around it. 

I'll fix that later but PR is welcome, basically we need to remove the comma [here](https://github.com/saberland/saber/blob/master/packages/saber/src/vue-renderer/index.js#L257)  when there're no pages.
